/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Assignemt_1;



import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import com.Person;
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
		EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersonPU");
		EntityManager entitymanager = emf.createEntityManager();
		Person obj = new Person();
		obj.setPersonName("Siddartha Gurugubelli");
		obj.setPersonEmail("siddarthagurugubelli@gmail.com");
		obj.setPersonPhone(7330700158l);
		
		
		entitymanager.getTransaction().begin();
		entitymanager.persist(obj);
		entitymanager.flush();
		entitymanager.getTransaction().commit();
	}
}